name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # script: eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa_ninh && cd ${{ secrets.PROJECT_PATH }} && git pull
          script: |
            cd ${{ secrets.PROJECT_PATH }} 
            git pull https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@github.com/ninhnguyen375/todolist.git